engines:
  pmd:
    custom_rulesets:
      - ruleset.xml
    file_extensions:
      apex:
        - .cls
        - .trigger
      visualforce:
        - .page
        - .component
      xml:
        - .xml